// <auto-generated />
namespace Update.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DATN : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DATN));
        
        string IMigrationMetadata.Id
        {
            get { return "202208260822120_DATN"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
