//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Update.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CVE
    {
        public string MaCVE { get; set; }
        public string MaHDH { get; set; }
        public string MoTa { get; set; }
        public Nullable<System.DateTime> NgayPhatHien { get; set; }
        public Nullable<decimal> MucDo { get; set; }
    
        public virtual HEDIEUHANH HEDIEUHANH { get; set; }
    }
}
