//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Update.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAYTINH
    {
        public string MaMT { get; set; }
        public string TenMT { get; set; }
        public string MaHDH { get; set; }
        public string MaPM { get; set; }
        public string MAC { get; set; }
        public string IP { get; set; }
    
        public virtual HEDIEUHANH HEDIEUHANH { get; set; }
    }
}
