//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Update.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIENBAN
    {
        public int id { get; set; }
        public string MaPM { get; set; }
        public string TenPhienBan { get; set; }
        public string NgayPhatHanh { get; set; }
    
        public virtual PHANMEM PHANMEM { get; set; }
    }
}
